export const GET_TRANSFERS = 'GET_TRANSFERS'
export const INIT_SEARCH_TORRENT_POSTS = 'INIT_SEARCH_TORRENT_POSTS'
export const GET_TORRENT_POSTS = 'GET_TORRENT_POSTS'
export const DOWNLOAD_TORRENT_POST = 'DOWNLOAD_TORRENT_POST'
